name: 🏷️ Update Package Version and Create Tag
on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "**"

jobs:
  tag:
    if: ${{ !contains(github.event.commits[0].message, 'chore(release):') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: bitflight-devops/shell-scripts@v2.2
        name: Install shell utility scripts

      - name: get email
        shell: bash
        env:
          commits: ${{github.event.commits[0].message}}
        run: |
          git config --global user.email "$(get_last_github_author_email 'jamie@bitflight.io')"
          git config --global user.name "$(get_last_github_author_name)"
          echo "commits: ${commits}"

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install project dependencies
        run: yarn install
      - run: yarn build
      - uses: undergroundwires/bump-everywhere@master
        with:
          commit-message: "chore(release): ⬆️ bump version to {{ version }}"
          git-token: ${{ secrets.GITHUB_TOKEN }}
          release-type: "release"
          release-token: ${{ secrets.RELEASE_TOKEN }}
