name: 🏷️ Update Package Version and Create Tag
on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  tag:
    if: ${{ !contains(github.context.commits[0].message, 'chore(release):') }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: bitflight-devops/shell-scripts@v2.2
        name: Install shell utility scripts

      - name: get email
        shell: bash
        run: |
          git config --global user.email $(get_last_github_author_email 'wearsafe.jenkins@gmail.com')
          git config --global user.name $(get_last_github_author_name)
          echo ${{github.context.commits[0].message}}

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn install
      - run: yarn build
      - uses: undergroundwires/bump-everywhere@master
        with:
          commit-message: 'chore(release): ⬆️ bump version to {{ version }}'
          git-token: ${{ secrets.GITHUB_TOKEN }}
          release-type: 'release'
          release-token: ${{ secrets.RELEASE_TOKEN }}
